name: Coq CI (Matrix root, explicit coqc path)
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq_image: [coqorg/coq:8.19.2, coqorg/coq:8.20.1]
    container:
      image: ${{ matrix.coq_image }}
      options: --user 0:0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show Coq version
        shell: bash
        run: |
          set -euxo pipefail
          echo "PATH=$PATH"
          if command -v /usr/local/bin/coqc >/dev/null 2>&1; then /usr/local/bin/coqc -v; else coqc -v; fi

      - name: Build FLT_new.v
        shell: bash
        run: |
          set -euxo pipefail
          if command -v /usr/local/bin/coqc >/dev/null 2>&1; then /usr/local/bin/coqc -Q . "" FLT_new.v; else coqc -Q . "" FLT_new.v; fi

      - name: Build FLT_old.v
        shell: bash
        run: |
          set -euxo pipefail
          if command -v /usr/local/bin/coqc >/dev/null 2>&1; then /usr/local/bin/coqc -Q . "" FLT_old.v; else coqc -Q . "" FLT_old.v; fi

      - name: Fail if any Admitted remain
        run: |
          if grep -R -n --include="*.v" 'Admitted\.' .; then
            echo "::error::Found Admitted"; exit 1; fi
